# Generated by Django 5.0.3 on 2024-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0003_alter_task_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timespend',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
