# Generated by Django 5.0.3 on 2024-03-13 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0006_alter_task_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 10, 12, 34, 376407, tzinfo=datetime.timezone.utc)),
        ),
    ]
